### ISSUE TITLE
client is not being added to client array

### ISSUE THREAD

**Issue by MathisBurger** [OmeChat/server#1]
The client hash is not being added to the array of client hashes in the user.json

**Comment by Kaktushose** [comment]
please tell me you are not using json to store your data

**Comment by MathisBurger** [comment]
I am using json, because I am only storing credentials. I do not think it`s worth to use a database for this kind of backend.
Furthermore the application will be hosted later as a docker container. So I want to save up server performance and storage by only using json for this small amount of data.
If the backend stores more data than I expected, I can switch to a database. But at the moment it does not make sense for me
